### ISSUE TITLE
Baixar currículo retornando 404

### ISSUE THREAD

**Issue by RafaelMotaAlvess** [pinuya/pinuya.dev#1]
A opção de baixar currículo na tela principal, ao clicar está retornando um erro 404

![erro](https://github.com/pinuya/pinuya.dev/assets/86445038/2e4e7a27-cf64-4476-9edd-7f6e8182b434)
![image](https://github.com/pinuya/pinuya.dev/assets/86445038/22627690-650b-4981-b10f-ecbce38049f7)

Suponho que o motivo do erro esteja relacionado ao PDF da pasta public não ter sido enviado para o domínio da vercel.

**Comment by pinuya** [comment]
A pasta public estava no dominio da vercel, o problema era a URL ela so funcionava localmente.

Antes: `/public/CurriculumTifany.pdf`
Depois: `<Link to={"/CurriculumTifany.pdf"} target="_blank">`

Obrigada pelo report!
